<a href="https://colab.research.google.com/github/ericmaniraguha/deep_learning_PyTorch/blob/00_pytorch_fundamentals/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 00. Start with Pytorch Fundamentals 

sources:

1. https://github.com/mrdbourke/pytorch-deep-learning

2. https://www.learnpytorch.io/ 

3. https://zerotomastery.io/courses/learn-pytorch/


In [1]:
!nvidia-smi

Tue May 30 13:46:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch 
print(torch.__version__)

2.0.1+cu118


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

## Introduction of Tensors
Create tensors 

Pytorch tensors are using 'torch.Tensor()' --https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_tensor.html#:~:text=PyTorch%3A%20Tensors,-A%20third%20order&text=A%20PyTorch%20Tensor%20is%20basically,used%20for%20arbitrary%20numeric%20computation.

In [4]:
# scalar 
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim 


0

In [6]:
# Get tensor back as Pytorch int 
scalar.item()

7

In [7]:
# vector
vector =  torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[11, 3],
                      [8,12]])
MATRIX

tensor([[11,  3],
        [ 8, 12]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([11,  3])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor


In [15]:
#TENSOR
TENSOR =  torch.tensor([
  [  [1,2,3],
    [4,5,6],
    [7,8,9]]
    ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors 

### Why random tensor?


A random tensor is a tensor with elements that are randomly generated according to a specific distribution or rule. Random tensors are commonly used in various areas of mathematics, statistics, and machine learning for several reasons:

Initialization: Random tensors are often used as initial values when training neural networks or other machine learning models. Initializing the model parameters with random values helps break symmetry and prevents the model from getting stuck in suboptimal solutions. By starting with random tensors, the learning process can explore different regions of the solution space.

Exploration: Random tensors are useful for exploring different possibilities and generating diverse samples. In many optimization algorithms or search algorithms, random tensors are used to explore the solution space, hoping to find better solutions or discover patterns and insights.

Probabilistic Modeling: Random tensors are fundamental for probabilistic modeling, where uncertainty is modeled using probability distributions. Random tensors can represent random variables and can be used to sample from probability distributions, enabling simulations, inference, and uncertainty quantification.

Noise Injection: Random tensors can be used to introduce noise into a system or data. Noise injection is often employed in data augmentation techniques to improve the generalization and robustness of machine learning models. Random tensors can also be used for regularization purposes, preventing overfitting by adding stochasticity to the learning process.

Stochastic Gradient Descent: Stochastic Gradient Descent (SGD) is a popular optimization algorithm used in training machine learning models. Random tensors play a crucial role in SGD by randomly sampling a subset of training data (known as a mini-batch) for each iteration. This randomness helps in achieving faster convergence and avoiding local minima.

Overall, random tensors provide a way to introduce randomness and variability into mathematical and computational systems, enabling exploration, uncertainty modeling, optimization, and other important tasks in various fields.


#### Random tensors 
why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers adjust those random numbers to better represent the data.

Start with random numbers  -> look at data -> update random numbers -> look at data -> update

https://pytorch.org/docs/stable/generated/torch.rand.html

In [19]:
# create a random tensor of size/ shape (3,4)

random_tensor =  torch.rand(3,4)
random_tensor

tensor([[0.3017, 0.2488, 0.8676, 0.7774],
        [0.4425, 0.4721, 0.4827, 0.5343],
        [0.2719, 0.7751, 0.8876, 0.8270]])

In [20]:
random_tensor.ndim

2

In [21]:
# create a random tensor of size/ shape (3,4)

random_tensor =  torch.rand(1, 3,4)
random_tensor

tensor([[[0.7935, 0.6956, 0.5792, 0.0823],
         [0.6845, 0.3687, 0.7499, 0.5070],
         [0.0695, 0.3655, 0.6353, 0.0953]]])

In [22]:
random_tensor.ndim

3

In [23]:
random_tensor.shape

torch.Size([1, 3, 4])

In [24]:
# create a random tensor of size/ shape (3,4)

random_tensor =  torch.rand(1,11,4)
random_tensor

tensor([[[0.6953, 0.9164, 0.9827, 0.8160],
         [0.4980, 0.9627, 0.3239, 0.1144],
         [0.7859, 0.4105, 0.1659, 0.4212],
         [0.0995, 0.6483, 0.3898, 0.7720],
         [0.6829, 0.1981, 0.5767, 0.3259],
         [0.7152, 0.0454, 0.7277, 0.8659],
         [0.5275, 0.2370, 0.6184, 0.6089],
         [0.4903, 0.3174, 0.8049, 0.0392],
         [0.1538, 0.0305, 0.7633, 0.2382],
         [0.6055, 0.2077, 0.0464, 0.8238],
         [0.3467, 0.3412, 0.2422, 0.8392]]])

In [25]:
random_tensor.ndim

3

In [26]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor =  torch.rand(244,244, 3) # heightt , width , color channel 
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([244, 244, 3]), 3)

In [27]:
torch.rand(3,3)

tensor([[0.7387, 0.7786, 0.3890],
        [0.9684, 0.5270, 0.0148],
        [0.5839, 0.1710, 0.2022]])


### Zeros and ones 
---



---



In [28]:
# create a tensor of all ones 
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros.dtype

torch.float32

In [30]:
# create a tensor of all ones 
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

#### Create a range of tensors and tensors like

In [32]:
# Use torch.range()
torch.arange(15)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Create a range start by range 
one_to_ten = torch.arange(start = 0, end = 10, step = 2)
one_to_ten


tensor([0, 2, 4, 6, 8])

In [35]:
#Create tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0])

#### Tensor datatypes

In [36]:
# float  tensor
float_32_tensor = torch.tensor([3.0, 6.6, 9.0], 
                               dtype =None, # what datatype is  the tensor
                               device =None, # What device is your tensor on 
                               requires_grad =False) # while i want pytorch to track the gradients or not
float_32_tensor

tensor([3.0000, 6.6000, 9.0000])

In computer science, the precision of a numerical quantity is a measure of the detail in which the quantity is expressed. This is usually measured in bits, but sometimes in decimal digits. It is related to precision in mathematics, which describes the number of digits that are used to express a value.

This is for differenciate the 16 bits floating point and 32 bits floating point.
Therefore, 32 bits floating is single precision while 16 bits floating is half precision.

Note: Tensor datatypes is one of the 3 big errors you willl run into with PyTorch and Deep learning:

1. Tnesor not right datatype
2. Tensors not right shape 
3. Tensors not on the right device

https://en.wikipedia.org/wiki/Precision_(computer_science)

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
# convert tensor 32 to 16 floats
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor 

tensor([3.0000, 6.6016, 9.0000], dtype=torch.float16)

In [39]:
multiply_tensors_with_diff_dtype  = (float_16_tensor * float_32_tensor)
multiply_tensors_with_diff_dtype

tensor([ 9.0000, 43.5703, 81.0000])

In [40]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [41]:
float_32_tensor * int_32_tensor

tensor([ 9.0000, 39.6000, 81.0000])

In [42]:
int_64_tensor = torch.tensor([3,6,9], dtype = torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [43]:
float_32_tensor * int_64_tensor

tensor([ 9.0000, 39.6000, 81.0000])

In [44]:
Long_tensor = torch.tensor([3,6,9], dtype = torch.long)
Long_tensor

tensor([3, 6, 9])

In [45]:
float_32_tensor * Long_tensor

tensor([ 9.0000, 39.6000, 81.0000])

### Getting information from tensors (tensor attributes)

1. Tnesor not right datatype - to do datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape 
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [46]:
## Create a tensor 

some_tensor =  torch.rand(3,4)
some_tensor

tensor([[0.1730, 0.1315, 0.3077, 0.2125],
        [0.0795, 0.4531, 0.2576, 0.0479],
        [0.3758, 0.1542, 0.7305, 0.5565]])

In [47]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [48]:
some_tensor.size()

torch.Size([3, 4])

In [49]:
# Find out details about some tensor 
print(some_tensor)
print(f'Datatype of tensors: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on : {some_tensor.device}')

tensor([[0.1730, 0.1315, 0.3077, 0.2125],
        [0.0795, 0.4531, 0.2576, 0.0479],
        [0.3758, 0.1542, 0.7305, 0.5565]])
Datatype of tensors: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on : cpu


In [50]:
# Change the devise of Tensors
new_device = torch.device("cuda:0")  # Example device, e.g., GPU 0
some_tensor = some_tensor.to(new_device)
some_tensor

tensor([[0.1730, 0.1315, 0.3077, 0.2125],
        [0.0795, 0.4531, 0.2576, 0.0479],
        [0.3758, 0.1542, 0.7305, 0.5565]], device='cuda:0')

#### Maninpulating Tensors (tensor operations)

## How to change the device of tensor
Tensor operations includes:
* Addition
* Substration
* Multiplication (element wise)
* Division
* Matrix

In [51]:
# Create a tensor
tensor =  torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [52]:
# multiply the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [53]:
# Substract the tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [54]:
# Try out Pytorch in build function 
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [55]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning: 

  * Element wise mutliplication
  * Matrix multiplication(dot pruduct)

  More information on multiplication matrices: https://www.cliffsnotes.com/study-guides/algebra/linear-algebra/matrix-algebra/operations-with-matrice

  There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensons** must match:
    * `(3, 2) @ (3, 2)` will not work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape pf **outer dimensions**:
    * `(2, 3) @ (3, 2)` -> `(2, 2)`
    * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [56]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2) ) # Error is causing my inner dimension which is not matching each other.

In [57]:
torch.matmul(torch.rand(3,2), torch.rand(2,2) ) 

tensor([[0.3695, 0.2817],
        [0.7429, 0.5748],
        [0.6275, 0.4768]])

In [58]:
torch.matmul(torch.rand(2,3), torch.rand(3,2) ) 

tensor([[0.7618, 0.7736],
        [1.1879, 0.8171]])

In [59]:
torch.matmul(torch.rand(2,10), torch.rand(10,3) ) 

tensor([[2.9851, 2.7193, 1.7019],
        [3.2790, 2.6253, 1.8248]])

In [60]:
torch.matmul(torch.rand(3,10), torch.rand(10,3) ) 

tensor([[2.0912, 2.3064, 2.5398],
        [2.3342, 2.4569, 2.4205],
        [2.8524, 2.7206, 3.0617]])

In [61]:
torch.matmul(torch.rand(2,10), torch.rand(10,15) ) 

tensor([[3.1804, 3.4463, 2.7515, 2.4441, 2.2152, 2.1139, 3.0406, 2.4737, 2.8098,
         2.4375, 3.4887, 3.2097, 2.3845, 3.0046, 3.4160],
        [3.6214, 3.0258, 2.6153, 3.2246, 1.8579, 2.2138, 2.8215, 3.0533, 2.1604,
         1.9809, 3.0328, 3.8199, 2.8235, 3.2651, 3.6822]])

In [62]:
# Element wise multiploication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [63]:
# Matrix Multiplication

torch.matmul(tensor, tensor )

tensor(14)

In [64]:
tensor

tensor([1, 2, 3])

In [65]:
tensor @ tensor

tensor(14)

In [66]:
# Matrix multiplication by hand 
1*1 + 2*2 + 3*3

14

In [67]:
%%time
value  = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.25 ms, sys: 58 µs, total: 1.31 ms
Wall time: 1.41 ms


In [68]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 797 µs, sys: 0 ns, total: 797 µs
Wall time: 4.37 ms


tensor(14)

### One of the most common errors in deep learning: shape error

https://byjus.com/maths/matrix-multiplication/#:~:text=Matrix%20multiplication%2C%20also%20known%20as,X%20%3D%20AB

In [69]:
# Shape for matrix multiplication 
tensor_A = torch.tensor (
  [  [1, 2],
    [3, 4],
    [5, 6]]
  
)

tensor_B = torch.tensor(
  [  [7, 10],
    [8, 11],
    [9, 12]]
)

torch.mum(tensor_A, tensor_B)

AttributeError: ignored

In [78]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [74]:
tensor_A.shape, tensor_B.shape # The reason is not running is that the inner values are not similar.

(torch.Size([3, 2]), torch.Size([3, 2]))

Solutions

In [77]:
# To fix the tensor shape issues, we can manipulate the sahpe of one of our tensors by using transpose, sitches the axes or dimensions of given tensor.

In [75]:
tensor_A, tensor_B.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [76]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

http://matrixmultiplication.xyz/

In [73]:
# The matrix multiplication operation works when tensor_B is transposed 
print(f'Original shapes : tensor_A = {tensor_A}, tensor_B = {tensor_B}')
print(f'New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match' )
print('Output:\n')
output = torch.chain_matmul(tensor_A, tensor_B.T)

torch.matmul(tensor_A, tensor_B.T)

Original shapes : tensor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]), tensor_B = tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:



/usr/local/lib/python3.10/dist-packages/torch/functional.py:1626: UserWarning: torch.chain_matmul is deprecated and will be removed in a future PyTorch release. Use torch.linalg.multi_dot instead, which accepts a list of two or more tensors rather than multiple parameters. (Triggered internally at ../aten/src/ATen/native/LinearAlgebra.cpp:1079.)
  return _VF.chain_matmul(matrices)  # type: ignore[attr-defined]


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

http://matrixmultiplication.xyz/

## Finding the min, max, mean, sum, etc(tensor aggregation)

In [96]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
# find the min and max
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [84]:
# find the mean 
torch.mean(x.type(torch.float32))

tensor(45.)

In [86]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [90]:
# find the sum of x 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [91]:
# find the min value at X index using agr
x.argmin()

tensor(0)

In [98]:
 x[0]

tensor(0)

In [99]:
# find the position in tensor that that has the maximum value with argmax()
x.argmax()

tensor(9)

In [100]:
x[9]

tensor(90)

In [101]:
x 

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Reshaping, stacking, squeezing and unsquzeeing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certian shape but keep the same memory as the original tensor 
* Squeeze - remove all `1` dimensions from a tensor 
* Unsqueeze - add a `1` dimensions to a target tensor 
* Permute -Return a view of the input with dimensions permited (sqapped) in a certain way.

In [104]:
#  let is create a tensor 
import torch
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [107]:
# Add an extra dimension
x_reshaped =  x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [110]:
# Add an extra dimension
x_reshaped =  x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [113]:
#  let is create a tensor 
import torch
x = torch.arange(1., 11)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [118]:
# Add an extra dimension
x_reshaped =  x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [122]:
# Change the view  = shares the memory as the orginal tensor
z = x.view(1, 10)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [125]:
# Changing z changes x (because a view of tensor shares the same memory as the original )

z [:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [127]:
# stacl tensor on top of each other 
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [134]:
# stacl tensor on top of each other 
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [140]:
# squeeze the tensor  - remove single dimensions with a targated tensor
x_squeezed = x_reshaped.squeeze()

print (f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])
New shape: torch.Size([10])


In [136]:
x_reshaped.shape

torch.Size([1, 10])

In [137]:
x_reshaped.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [138]:
x_reshaped.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
import torch

# torch permute  - rearranges the dimension of a target tensor in a specified order 
x_original =  torch.rand(size = (224, 224, 3)) # height, width, color_channels 

# permute the original tensor to rearrange the axis (or dim) order
x_permuted =  x_original.permute(2, 0, 1) # shift axis 0 ->1, 1 -> 2,  2->0

print(f'Previous shape: {x_original.shape}') 
print(f'New shape: {x_original.shape}') # [color_channels, hight, width]



Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([224, 224, 3])


In [4]:
x_original[0, :, 0]

tensor([0.1491, 0.2305, 0.1547, 0.8970, 0.6528, 0.8442, 0.5601, 0.1407, 0.5675,
        0.1256, 0.9533, 0.5821, 0.5981, 0.6548, 0.0789, 0.7665, 0.0483, 0.7061,
        0.8038, 0.3952, 0.0211, 0.0083, 0.1511, 0.5933, 0.7741, 0.0954, 0.7921,
        0.3593, 0.0525, 0.5995, 0.4947, 0.0022, 0.9778, 0.6941, 0.6021, 0.1150,
        0.9962, 0.3511, 0.7572, 0.0415, 0.2774, 0.0646, 0.3342, 0.3939, 0.7868,
        0.6456, 0.4103, 0.3539, 0.6118, 0.2982, 0.2640, 0.0155, 0.8843, 0.8045,
        0.2207, 0.8468, 0.1958, 0.7753, 0.5665, 0.2824, 0.0832, 0.8722, 0.1959,
        0.8098, 0.3960, 0.4996, 0.7141, 0.3594, 0.5566, 0.0190, 0.5561, 0.3065,
        0.7674, 0.2210, 0.2828, 0.6665, 0.0907, 0.0304, 0.6952, 0.8245, 0.6465,
        0.9635, 0.8216, 0.2618, 0.1597, 0.8416, 0.7841, 0.7650, 0.4469, 0.3802,
        0.6984, 0.6190, 0.7261, 0.3875, 0.6489, 0.7072, 0.9709, 0.1182, 0.4777,
        0.4085, 0.6792, 0.2292, 0.3296, 0.7547, 0.5421, 0.8480, 0.5784, 0.9381,
        0.5818, 0.4682, 0.3452, 0.3855, 

In [5]:
x_original[0, 0, 0]

tensor(0.1491)

In [8]:
x_original[0, 0, 0] = 7282187
x_original[0, 0, 0]

tensor(7282187.)

In [9]:
x_original[0, 0, 0] = 7282187
x_original[0, 0, 0], x_permuted[0, 0, 0 ]

(tensor(7282187.), tensor(7282187.))

## Indexing (select data from tensor)

indexing with Pytorch is similar to indexing with NumPy

In [12]:
# create a tensor 
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [15]:
# let's index on the most middle bracket (dim = 1)

x[0][0]

tensor([1, 2, 3])

In [14]:
# let's index on the most inner bracket (last dimension)

x[0][0][0]

tensor(1)

In [16]:
x[1][1][1] # This is out of bound as our dimension is 1 where we can index only at 0 for the 1st array 

IndexError: ignored

In [20]:
x[0][2][2]

tensor(9)

In [21]:
# you can also use: "to select "all" of a target dimension"
x[:,0]

tensor([[1, 2, 3]])

In [22]:
# Get all values of 0th and 1st dimension  but only index 1 of the 2nd dimension 
x[:,:,1]

tensor([[2, 5, 8]])

In [23]:
#Get all values of the 0 dimension but only the 1st index value of 1st and 2end dimension
x[:, 1, 1]

tensor([5])

In [24]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension

x[0,0,:]

tensor([1, 2, 3])

In [32]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [33]:
# Index on x to return 9

x[0,2,2]

tensor(9)

In [36]:
# index on x to return 3, 6, 9
x[0,:,2]


tensor([3, 6, 9])

## PyTorch tensors and Numpy 

Numpy is a popular scientific python numerical computing library. 
And because of this, PyTorch has functionality ty to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [44]:
# Numpy array to tensor 
import torch
import numpy as np

array  =  np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: When converting from numpy -> pytorch, pytorch reflect reference numpy's default datatype of float64 unless specified otherwise  
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [45]:
array.dtype

dtype('float64')

In [46]:
torch.arange(1.0, 8.0)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [47]:
torch.arange(1.0, 8.0).dtype

torch.float32

Chnage the value of array, what will this do to `tensor`?

In [48]:
# Here does not affect values of tensor while we change the value of array 
array  =  array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
# Tensor to Numpy array

tensor =  torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [52]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductibility (try to take random out of random) 

short how a neural network learns:

1. art with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again ....
To reduce the randomness in neural networks and PyTorch comes the conecept of a **random seed.**
Essentially what the random seed does is "flavour" the randomness

In [53]:
torch.rand(3,3)

tensor([[0.8617, 0.2659, 0.9411],
        [0.4592, 0.6703, 0.5459],
        [0.2904, 0.3714, 0.8476]])

In [61]:
import torch 

#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4663, 0.6318, 0.1708, 0.6987],
        [0.9958, 0.3850, 0.3833, 0.5082],
        [0.3759, 0.0877, 0.8879, 0.2526]])
tensor([[0.8447, 0.6100, 0.3554, 0.4537],
        [0.5320, 0.0684, 0.9470, 0.5114],
        [0.7189, 0.7833, 0.5901, 0.2835]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [62]:
# let make a random but reproduceble tensor 
import torch

# set the random seed 

RANDOM_SEED  = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [64]:
# Seed each time with randomness 

RANDOM_SEED  = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Resources: 
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running PyTorch objects on the GPUs and making faster computation
GPUs = Faster compution on numbers, thanks 
to CUBA + NVIDIA hardware + PyTorch workinmg behind the scenes to make everything hunky doy (good)



### 1. Getting a GPU
1. Use Google colab pro for free GPU (option to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purshasing a GPU, there's lots of options ..., see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing Cloud computing (AWS, GCP, Azure) these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUB) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.

In [1]:
!nvidia-smi

Wed May 31 09:47:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch


In [3]:
# Check for GPU access pytorch 
import torch 
torch.cuda.is_available()


True

If the above output `"cuda"` it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output `"cpu"`, our PyTorch code will stick with the CPU.

https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code

In [6]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

In [8]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Notice the second tensor has `device='cuda:0'`, this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be 'cuda:0' and `'cuda:1'` respectively, up to `'cuda:n'`).

#### 4. Moving tensors back to the CPU

In [12]:
#If tensor is on CPU, can't transform it to Numpy

tensor_on_gpu.numpy()

NameError: ignored

Instead, to get a tensor back to CPU and usable with NumPy we can use `Tensor.cpu().`

This copies the tensor to CPU memory so it's usable with CPUs.

In [12]:
tensor_on_cpu =  tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Sources: 
1. https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

## Exercises 


## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on `torch.Tensor.`
* The documentation on `torch.cuda.`

## 2. Create a random tensor with shape (7, 7).

In [1]:
# Import torch
import torch 

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.1976, 0.0994, 0.0897, 0.9688, 0.6487, 0.7881, 0.0415],
         [0.3271, 0.3003, 0.9438, 0.0961, 0.3227, 0.8821, 0.1478],
         [0.6507, 0.8873, 0.0118, 0.9050, 0.2887, 0.9936, 0.7059],
         [0.5886, 0.0127, 0.3478, 0.0976, 0.3261, 0.7931, 0.0769],
         [0.5320, 0.6422, 0.6715, 0.5311, 0.6046, 0.1984, 0.5567],
         [0.6258, 0.3873, 0.1393, 0.1125, 0.8260, 0.2126, 0.6448],
         [0.1283, 0.3716, 0.2903, 0.1535, 0.1373, 0.1478, 0.1687]]),
 torch.Size([7, 7]))

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with `shape (1, 7)` (hint: you may have to transpose the second tensor).

In [2]:

# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[1.0216],
         [1.0937],
         [1.4867],
         [0.8786],
         [0.7226],
         [0.6817],
         [0.3494]]),
 torch.Size([7, 1]))

## 4. Set the random seed to `0 and do 2 & 3 over again.`

The output should be:



In [4]:

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

## 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for ` torch.cuda `for this one)

* If there is, set the GPU random seed to 1234.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
* The output should look like:

In [8]:

# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

## 8. Find the maximum and minimum values of the output of 7.


In [9]:

# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

## 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
